### ISSUE TITLE
SQL push-down with VARCHAR, DATE, TIME and TIMESTAMP types

### ISSUE THREAD

**Issue by zz22394** [Teradata/presto#421]
1) Teradata 152t version
**Limited SQL push-down**
> Presto does not “push-down” aggregate calculations to PostgreSQL or MySQL
http://teradata.github.io/presto/docs/current/release/release-0.152.1-t.html
2) FB 0.148 later version
https://prestodb.io/docs/current/release/release-0.148.html
> MySQL and PostgreSQL Changes : Push down predicates for VARCHAR, DATE, TIME and TIMESTAMP types.

> Hive : Push down filters for columns of type DECIMAL.

Our question is:
In my opinion, Teradata 152t should be rebased with FB 0.152 and with Teradata enhanced patches.
however in 152t we can't find new push downs in MySQL, is Teradata 152t document old or 152t didn't merged the MySQL VARCHAR push down patches?

**Comment by cawallin** [comment]
152t has all of the patches from upstream 0.148, so predicates on VARCHAR, DATE, TIME, and TIMESTAMP should be pushed down for MySQL. However, aggregations are not yet pushed down either by the upstream version of Presto or the Teradata version. Does that clarify things?

**Comment by zz22394** [comment]
Oh, I get it.
I mistook the difference between "aggregate push down" and "predicate push down".

Thanks for your explanation!

**Comment by cawallin** [comment]
Looks like this is settled, closing the issue.
