### ISSUE TITLE
Is this a bug about get query peak memory usage ?

### ISSUE THREAD

**Issue by zz22394** [Teradata/presto#439]
Dear team

We are considering to get query peak memory usage.
I tried to run a query with Hive connector.
![Coordinator UI](https://cloud.githubusercontent.com/assets/516268/20597018/b6c4e8e0-b284-11e6-919f-163511c9fa6a.png)
However found Peak Memory always be 0B.

In [google user groups](https://groups.google.com/forum/#!searchin/presto-users/Memory$20Stats|sort:date/presto-users/HS2yF_lXaSY/FShiP4YNAwAJ) , it is also pointed out that "Presto coordinator UI shows you the peak memory usage of a query and current memory usage of a query".

Is this a bug in displaying Peak Memory?

**Comment by petroav** [comment]
@zz22394 what version of Presto are you seeing this on?

**Comment by anusudarsan** [comment]
Confirmed that this issue is reproducible with 152t. https://github.com/prestodb/presto/issues/6436 is the relevant issue, and was fixed in 0.155 version of Presto (PR https://github.com/prestodb/presto/pull/6455). So the fix should be available in our Q4 release.

**Comment by zz22394** [comment]
@petroav we are using 152t
@anusudarsan thanks for your investigating!

**Comment by petroav** [comment]
@zz22394 closing this for now, let us know if you need more info/help.
