### ISSUE TITLE
Can't find /etc/presto/event-listener.properties with default settings

### ISSUE THREAD

**Issue by zz22394** [Teradata/presto#500]
Dear team,

I made my own event-listener, and put the event-listener.properties in /etc/presto/
However Presto can't find event-listener.properties.
Also, the log.properties is not read by presto because there is no setting to use it in presto-server-rpm.

I checked the launcher.py , and found it is always checking files under [INSTALL_FOLDER]/etc,([launcher.py](http://https://github.com/airlift/airlift/blob/master/launcher/src/main/scripts/bin/launcher.py#L168))

By presto-admin, it is putting all the properties files in /etc/presto/,
So I think it is better to create a symbolic link in presto-server-rpm/postinstall, how do you think about this?
https://github.com/prestodb/presto/blob/master/presto-server-rpm/src/main/rpm/postinstall#L21
```
ln -snf /etc/presto/ /usr/lib/presto/etc
```

**Comment by cawallin** [comment]
@zz22394 we already did this symlink, it should be in 0.164 and will definitely be in the next Teradata release :) https://github.com/prestodb/presto/pull/7077

**Comment by zz22394** [comment]
Thanks to your reply.
The presto community is so fast to fix a bug! 👍

**Comment by maciejgrzybek** [comment]
This is similar to https://github.com/Teradata/presto/issues/440.
Both are solved already and as @cawallin mentioned, next TD release will have a proper patch included. :)
Thanks for the report, @zz22394!
