### ISSUE TITLE
Does Teradata Presto ODBC driver support prepared statements?

### ISSUE THREAD

**Issue by nmahadevuni** [Teradata/presto#611]
We setup the TD Presto ODBC driver but see that prepared statements fail. I see that JDBC driver supports it. Doesn't the ODBC drivers have the support?

**Comment by cawallin** [comment]
The Teradata ODBC driver does support prepared statements, it should work the same as the JDBC driver. For questions about the TD drivers, please post here with a stacktrace, what version of Presto/the drivers, and details about the setup: http://community.teradata.com/t5/Presto/bd-p/Presto.
